---
- name: Generate an HTML report from Jinja template with unreachable/failed hosts
  hosts: all
  gather_facts: true
  vars:
    # Email settings
    email_subject: Patching Report
    email_host: smtphost
    email_from: system@email.com
    email_to: user@email.com

    # CSV settings
    csv_path: /tmp
    csv_filename: report.csv
    headers: Hostname,Distro Ver,Kernel Ver,Last Rebooted,Status

  tasks:
    - name: Gather facts about all hosts
      ansible.builtin.setup:
        register: all_hosts

    - name: Calculate unreachable and failed hosts
      set_fact:
        unreachable_hosts: "{{ all_hosts.ansible_play_hosts_all | difference(all_hosts.ansible_play_hosts) }}"
        failed_hosts: "{{ all_hosts.ansible_play_hosts_all | intersect(all_hosts.ansible_play_failed) }}"

    - name: Build CSV entries for all hosts
      block:
        - set_fact:
            host: "{{ item.hostname }}"
            distro: "{{ item.ansible_distribution_version }}"
            kernel: "{{ item.ansible_kernel }}"
            reboot: "{{ item.msg | regex_replace('^.* (.*)$', '\\1') | default('') }}"  # Extract reboot info from msg (optional)
            status: "{{ item.status }}"
          vars:
            item: "{{ all_hosts.results }}"
        - name: Add host entry to CSV
          ansible.builtin.lineinfile:
            dest: "{{ csv_path }}/{{ csv_filename }}"
            line: "{{ host }},{{ distro }},{{ kernel }},{{ reboot }},{{ status }}"
            create: true
            state: present
            delegate_to: localhost

    - name: Read in CSV to variable
      community.general.read_csv:
        path: "{{ csv_path }}/{{ csv_filename }}"
        register: csv_file
        delegate_to: localhost
        run_once: true

    - name: Send Email
      community.general.mail:
        host: "{{ email_host }}"
        from: "{{ email_from }}"
        port: 25
        to: "{{ email_to }}"
        subject: "[Ansible] {{ email_subject }}"
        body: "{{ lookup('template', 'report.html.j2') }}"
        attach: "{{ csv_path }}/{{ csv_filename }}"
        subtype: html
        delegate_to: localhost
        run_once: true
